# Generated by Django 5.0.4 on 2024-04-13 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('crop_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name_hi', models.CharField(help_text='Crop Name Hindi', max_length=100)),
                ('crop_name', models.CharField(help_text='Crop Name.', max_length=80)),
                ('image_thumbnail', models.CharField(help_text='image thumbnail.', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SaleReceipt',
            fields=[
                ('receipt_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandi_id', models.IntegerField(default=0, help_text='Mandi Id')),
                ('mandi_name', models.CharField(help_text='Mandi Name', max_length=80)),
                ('mandi_name_hi', models.CharField(help_text='Mandi Name Hindi', max_length=80)),
                ('receipt_date', models.DateTimeField(help_text='Timestamp at when Receipt is generated.')),
                ('quantity', models.FloatField(help_text='Quantity.')),
                ('user_id', models.UUIDField(help_text='User Id.')),
                ('booklet_number', models.CharField(help_text='Booklet Number.', max_length=100)),
                ('receipt_image_url', models.URLField(help_text='S3 URL of receipt image.')),
                ('is_approved', models.BooleanField(default=False, help_text='is receipt approved.')),
                ('crops', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='gram_server.crops')),
            ],
        ),
    ]
